config/routes.rb
Iblog::Application.routes.draw do
  
  root :to => "articles#index"
  resources :articles do 
    resources :comments
  end
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signup', to: 'users#new'
  match '/signout', to: 'sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :title 
 
 validates :title,:body, :presence => true
 validates_uniqueness_of :title 
 
 has_many :comments , :dependent => :destroy
 serialize :body
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  attr_accessible :body,:article_id,:user_id
  
  validates :article_id , :user_id ,:presence => true
  # validates :length => {:minimum =>5}
  
end

app/models/user.rb
class User < ActiveRecord::Base
   attr_accessible :username, :email , :password ,:password_confirmation
   has_secure_password

   before_save :create_remember_token

   validates :username ,:presence =>true ,:length =>{:maximum => 50}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email,:presence => true , :format  => {:with => VALID_EMAIL_REGEX }, :uniqueness => { :case_sensitive => true } 
   validates :password , :password_confirmation , :presence =>true 
   validates :password , :length => {:minimum => 6 }

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  include SessionsHelper


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # GET /articles
  # GET /articles.json
  require 'net/http'
  require 'oauth2'
  def index
    
    # api_client_obj = OAuth2::Client.new('1028167159482.apps.googleusercontent.com','DX91zikpNgET_mZA1cctablE', {:site => 'https://www.googleapis.com/'})
    # api_access_token_obj = OAuth2::AccessToken.new(api_client_obj, 'ya29.AHES6ZS0mtz4QJhii8XQGyNZ0LepD1ep5dmKi_MrkW0Hcw')
    # response=api_access_token_obj.post('/tracks/v1/geofences/create',{ :geofences =>[ { :name => "Inside" , :polygon => { :invert => false , :loops => [ { :vertices => [{:lat=> 45, :lng => -111 },
    #                                      { :lat=> 45, :lng => -104 },{ :lat=> 41,:lng => -104 }, { :lat=> 41, :lng => -111 } ]}]} }]})

    # puts response.to_s
    
    @articles = Article.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @articles }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @article = Article.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @article }
    end
  end

  # GET /articles/1/edit
  def edit
    @article = Article.find(params[:id])
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render json: @article, status: :created, location: @article }
      else
        format.html { render action: "new" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  include SessionsHelper
  def index
     @article = Article.find(params[:article_id])
    @comments = @article.comments

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    puts @comment.id

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @article = Article.find(params[:article_id])
    @comment = Comment.new(:article_id => @article.id)
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

 
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.build(params[:comment])
    @comment.user_id=current_user.id
    respond_to do |format|
      if @comment.save
        format.html { redirect_to(@article, :notice => 'Comment was successfully created.') }
        format.xml  { render :xml => @article, :status => :created, :location => @article }
      else
        format.html { redirect_to(@article, :notice => 
        'Comment could not be saved. Please fill in all fields')}
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
 
 def update
    @comment = Comment.find(params[:id])
    @article = @comment.article
    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to(@article, :notice => 'Comment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @comment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json

def destroy
    @comment = Comment.find(params[:id])
    @article = Article.find(params[:article_id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to(@article, :notice => 'Comment was successfully deleted.') }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      # Sign the user in and redirect to the user's show page.
      sign_in user
      redirect_to root_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
include SessionsHelper

def show
   
end

def new
  	@user= User.new
end

def create 
   @user=User.new(params[:user])
   if @user.save
      sign_in @user
      flash[:success] = "Welcome to the iblog!"
      redirect_to root_path
   else
      render 'new'
   end

end

def update 

end

def destroy

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
  	puts "entered sign_out"
    self.current_user = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/users_helper.rb
module UsersHelper


   def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
   end

end

app/views/articles/_article.html.erb
<div class="article">
  <h1 id='title'><%= article.title %></h1>
  <p class='postmetadata'>created by admin at <%=article.created_at.to_s %></p>


<a href="https://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="rajachinthan">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>

<a href="https://twitter.com/rajachinthan" class="twitter-follow-button" >Follow @rajachinthan</a>
<script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>


 


  <div id="body"><%= article.body.html_safe %></div>
   <%articlepath="/articles/"+article.id.to_s%>
  <a id="showlink" href="<%=articlepath%>">showarticle</a> <!-- see newarticle link for other way of doing it -->
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
   <%= f.text_area :body ,:class => "tinymce" ,:rows => 40, :cols => 120 %>
   <script type="text/javascript">
      tinyMCE.init({
        mode: 'textareas',
        theme: 'advanced',
        theme_advanced_disable: "code"

      });
    </script>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class='allpostsheading'>
<span class="allblogs">Iblog</span>
<nav>
 <ul id='firstlist'>
 	<li>Home
       <ul>
         <li><a href="<%=new_article_path%>">New article</a></li>
         <li>link2</li>
         <li>link3</li>
       </ul> 
     </li>  
  	<li>Portfolio
        <ul>
         <li>link4</li>
         <li>link5</li>
         <li>link6</li>
        </ul>
     </li>   
 	<li>BlogPosts</li>
 	<li>About</li>
 	<li>Contact</li>
 	<li>Recent</li>
 	<li>Research</li>
 	<li>About me</li>
 </ul>	
</nav>	
</div>
<%= render @articles %>
<br />
<%= link_to 'New Article', new_article_path, { :class => 'newarticle' }%>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <h1><%= @article.title %></h1>
</p>

<p>
  <%= @article.body.html_safe %>
</p>


<h2>Comments</h2>
<%= render :partial => @article.comments %>
<br />
<h2> Add Comment </h2>
<%= form_for([@article, @article.comments.build]) do |f| %>
<div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
</div>
  <%if signed_in? %>
  <p><%= f.submit %></p>
  <p><%= link_to "Sign Out",signout_path %>
  <% else %>
  <%=link_to "Sign In" , signin_path %>
  <%end %>
<% end %>

<br />
<%=link_to "All Articles" , articles_path %>

app/views/comments/_comment.html.erb
  
  <% user=User.find(comment.user_id) %>
  <p>
  <%= user.username %><br />
  <%= image_tag("user1.png", :size => "8*8") %>  
  
  </p>
  <p>
    <%=comment.body %>
  </p>

<%= link_to 'Edit', edit_article_comment_path(@article, comment) %> |
<%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :article %><br />
    <%= f.text_field :article %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= form_for([:article, @comment]) do |f| %>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Body</th>
    <th>Article_id</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.id %></td>
    <td><%= comment.body %></td>
    <td><%= comment.article_id %></td>
    <td><%= link_to 'Show', article_comment_path(@article,comment) %></td> -->
    <td><%= link_to 'Edit', edit_article_comment_path(@article, comment) %> |</td>
    <td><%= link_to 'Delete', article_comment_path(@article, comment), :confirm => 'Are you sure?', :method => :delete %>
</td>
  </tr>
<% end %>
</table>

<br />

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path(params[:article_id]) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>UserID:</b>
  <%= comment.user_id %>
  </p>
<p>
  <b>Body:</b>
  <%= @comment.body %>
</p>

<p>
  <b>Article:</b>
  <%= @comment.article %>
</p>


<%= link_to 'Edit', edit_article_comment_path(@article, @comment) %> |
<%= link_to 'Back', article_comments_path(@article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iblog</title>

 <%= stylesheet_link_tag "stylesettings" ,:media =>"screen"%>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= tinymce_assets %>
  <script type="text/javascript" src="/assets/tinymce.js">
  </script>
</head>
<body>
 <script src="//connect.facebook.net/en_US/all.js"></script>
<div id="fb-root"></div>
 <script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '478479238873163', // App ID from the App Dashboard
      channelUrl : 'localhost:3000', // Channel File for x-domain communication
      status     : true, // check the login status upon init?
      cookie     : true, // set sessions cookies to allow your server to access the session?
      xfbml      : true  // parse XFBML tags on this page?
    });

    // Additional initialization code such as adding Event Listeners goes here

  };

  // Load the SDK's source Asynchronously
  // Note that the debug version is being actively developed and might 
  // contain some type checks that are overly strict. 
  // Please report such bugs using the bugs tool.
  (function(d, debug){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all" + (debug ? "/debug" : "") + ".js";
     ref.parentNode.insertBefore(js, ref);
   }(document, /*debug*/ false));
</script>

<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=478479238873163";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<div class= "container">
  <div class="posts" id="content">
    <%= yield %>
  </div>
  <div class="span-4 last" id="sidebar"></div>
</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>